gvizfib: gvizfib.cpp
	g++ gvizfib.cpp C:\maximum\library\gvizlib\gvizlib.cpp -IC:\maximum\library\gvizlib
gviz: gviz.cpp
	g++ gviz.cpp C:\maximum\library\gvizlib\gvizlib.cpp -IC:\maximum\library\gvizlib
